### ISSUE TITLE
Account register/login problem

### ISSUE THREAD

**Issue by CoolJJ** [TuyaInc/tuyasmart_home_android_sdk#11]
你好 我嘗試使用demo註冊一個帳戶
但始終不能收到註冊碼

後來我嘗試下載play store上的app(塗鴉智能)
就可以註冊帳戶成功並且登入

btw, 使用這個帳戶也不能登入demo版
請問demo版部分我需要調整或做什麼嗎？

**Comment by NextApp** [comment]
手机账号发我一下，我查查日志看看

**Comment by CoolJJ** [comment]
> 手机账号发我一下，我查查日志看看

Cool_Lin@ioshop.com.tw 
麻煩了

**Comment by mimimumu** [comment]
https://github.com/TuyaInc/tuyasmart_home_android_sdk/blob/master/TuyaSmartHomeSdkDemo/app/src/main/AndroidManifest.xml

请把对应TUYA_SMART_APPKEY ，TUYA_SMART_SECRET替换为你自己申请的。
<meta-data
            android:name="TUYA_SMART_APPKEY"
            android:value="*******" />
        <meta-data
            android:name="TUYA_SMART_SECRET"
            android:value="******" />

**Comment by mimimumu** [comment]
https://github.com/TuyaInc/tuyasmart_home_android_sdk/blob/master/TuyaSmartHomeSdkDemo/app/build.gradle
applicationId 也改为你自己对应的。

**Comment by CoolJJ** [comment]
謝謝

**Comment by MrAhsan1** [comment]
I had done all these changes but I'm not able to register.

**Comment by avi3438** [comment]
After making the changes too while sign up no verification code is received neither on email nor on mobile, a toast pops up stating "Permission validation failed"
