### ISSUE TITLE
3.13.0 升级 3.14.x 指南 · GitBook

### ISSUE THREAD

**Issue by mimimumu** [TuyaInc/tuyasmart_home_android_sdk#112]
https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/zh-hans/resource/Update_3_14_0.html

**Comment by yiyayiya** [comment]
当连接的wifi 不能上网时,必现bug

06-08 17:27:11.345 21578 21649 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.StringBuilder java.lang.StringBuilder.append(java.lang.String)' on a null object reference
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at com.tuya.smart.android.network.http.HttpEventListener.recordEventLog(HttpEventListener.java:137)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at com.tuya.smart.android.network.http.HttpEventListener.dnsStart(HttpEventListener.java:194)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:182)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:215)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:250)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-08 17:27:11.345 21578 21649 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:784)

**Comment by mimimumu** [comment]
https://github.com/TuyaInc/tuyasmart_home_android_sdk/issues/108#issuecomment-640518551
