### ISSUE TITLE
设备添加定时问题

### ISSUE THREAD

**Issue by YY1989YY** [TuyaInc/tuyasmart_home_android_sdk#12]
调用该方法TuyaHomeSdk.getTimerManagerInstance().addTimerWithTask(）
所传参数：taskName:taskPlug,loops:1111111,devId:002003545ccf7f350f74,dpId:{"4":true},time:13:50
结果：定时添加成功，但是定时没有起到效果
备注：定时列表获取的数据如下：{"mTimerList":[{"mDate":"00000000","mDpId":"{\"4\":true}","mLoops":"1111111","mStatus":1,"mTime":"13:50","mTimerId":"00000064jo","mValue":"{\"{\\\"4\\\":true}\":true}"}],"mTimerTaskStatus":{"mIsOpen":true,"mTimerName":"taskPlug"}}

**Comment by blitzfeng** [comment]
> 调用该方法TuyaHomeSdk.getTimerManagerInstance().addTimerWithTask(）
> 所传参数：taskName:taskPlug,loops:1111111,devId:002003545ccf7f350f74,dpId:{"4":true},time:13:50
> 结果：定时添加成功，但是定时没有起到效果
> 备注：定时列表获取的数据如下：{"mTimerList":[{"mDate":"00000000","mDpId":"{"4":true}","mLoops":"1111111","mStatus":1,"mTime":"13:50","mTimerId":"00000064jo","mValue":"{"{\"4\":true}":true}"}],"mTimerTaskStatus":{"mIsOpen":true,"mTimerName":"taskPlug"}}

从云端查到的日志13:49多以后将{"4":true}推给设备了，请确定设备是否在线，可以多尝试几次，看下是否能复现

**Comment by YY1989YY** [comment]
这是新增的定时
{"mTimerList":[{"mDate":"00000000","mDpId":"{\"4\":true}","mLoops":"1111111","mStatus":1,"mTime":"17:13","mTimerId":"00000065uo","mValue":"{\"{\\\"4\\\":true}\":true}"},{"mDate":"00000000","mDpId":"{\"3\":true}","mLoops":"1111111","mStatus":1,"mTime":"17:15","mTimerId":"00000065up","mValue":"{\"{\\\"3\\\":true}\":true}"},{"mDate":"00000000","mDpId":"{\"2\":false}","mLoops":"1111111","mStatus":1,"mTime":"17:18","mTimerId":"00000065uq","mValue":"{\"{\\\"2\\\":false}\":true}"}],"mTimerTaskStatus":{"mIsOpen":true,"mTimerName":"taskPlug"}}

结果：设备没有反应。onDpUpdate调用了，但是返回的dps:{"1":false,"2":false,"3":false,"4":false,"5":true,"6":0}

**Comment by blitzfeng** [comment]
请问硬件是使用我们嵌入式的SDK开发吗，最好留下邮箱，方便了解具体细节

**Comment by YY1989YY** [comment]
是绑定的你们涂鸦的排插
