### ISSUE TITLE
不同类型的SDK的区别

### ISSUE THREAD

**Issue by YY1989YY** [TuyaInc/tuyasmart_home_android_sdk#13]
你好，问一下，安卓版的home_sdk和没有home的sdk，除了没有家庭管理之外，还有其他区别吗。由于没有home的sdk和我们项目中的库冲突，所以我用的home_sdk,但是我们项目中没有家庭管理，是默认的，有什么影响吗

**Comment by NextApp** [comment]
Home SDK 所有接口都是基于家庭纬度的。 你如果没有家庭界面的话，可以给用户默认创建个家庭
