### ISSUE TITLE
安卓版tuyasmart-2.9.4的问题

### ISSUE THREAD

**Issue by YY1989YY** [TuyaInc/tuyasmart_home_android_sdk#14]
1.不停报错
02-28 18:11:15.867 11220-11220/com.jcg.iotlink E/Tuya: MqttServerManager errorCode: F005 error: cannot start service com.tuya.smart.mqtt.MqttService
2.分享失败
返回的信息confirmInviteFailed---errorCode:NOT_EXISTS,errorMsg:分享邀请不存在
3.有分享成功过一次，但是总是出现session过期

**Comment by NextApp** [comment]
1、MQTTService找不到导致的，你看看apk里面的manifest有配置吗？

**Comment by YY1989YY** [comment]
集成tuyasmart-2.9.4版本的sdk，添加分享步骤如下
1.调用TuyaHomeSdk.getDeviceShareInstance().inviteShare(devId,shared_account,countryCode,mITuyaResultCallback)
2.邀请成功后调用
 TuyaHomeSdk.getUserInstance().loginOrRegisterWithUid(countryCode, shared_account, psw,true, mLoginCallback)
3.登录成功后调用TuyaHomeSdk.getDeviceShareInstance().confirmShareInviteShare(mShareId,mIResultCallback)

结果：分享成功后，回到获取分享列表页面返回的数据queryDeviceFailed---errorMsg:权限校验不通过。
获取分享列表的接口 getDeviceShareInstance().queryDevShareUserList(devId, mITuyaResultCallback)

**Comment by blitzfeng** [comment]
1.要确认分享步骤中1属于A用户的调用逻辑，2、3步骤是B用户的调用逻辑
2.新旧uid登录的区别是旧的uid第一次登录之后要创建家庭，之后才能调用一些其他接口比如获取设备列表、场景动作等；新的uid登录会默认创建一个家庭，不需要再单独调用创建家庭接口。如果之前用的是旧的uid登录接口再使用新接口可能会引发一些问题。
3.建议：如果使用新的uid接口，要替换所有旧的uid接口，也要去掉createHome创建家庭等接口，使用新测试账户测试以免受之前数据影响。或者步骤2使用旧的uid接口

**Comment by YY1989YY** [comment]
不是很明白，你说的1属于A用户的调用逻辑，2、3步骤是B用户的调用逻辑。你的意思是1中传的帐号是分享着帐号；2/3用的是被分享者帐号

后面说的登录需要统一对吧，好的。还有需确认下ios的登录和android的登录需要统一吗，不统一的话会引起其他的问题吗

**Comment by blitzfeng** [comment]
是的，1中帐号是分享着帐号；2/3用的是被分享者帐号
ios和android也要统一的，不统一的话会创建多个家庭，如果进入另一个家庭，原来家庭的设备就获取不到。
登录接口不要频繁调用，有可能引发session异常

**Comment by YY1989YY** [comment]
你说的A用户和B用户是指：比如我是A用户想分享当前设备给你，首先邀请你分享，邀请成功后返回shareId；B用户你需要打开APP输入shareId，还是在代码中操作以上3步

**Comment by blitzfeng** [comment]
这要看你们想要实现的邀请分享机制了，既可以让用户输入shareId，也可以在代码中实现。
举例A、B用户是说明分享邀请的逻辑，这三个接口不是由同一个用户触发的

**Comment by YY1989YY** [comment]
我们的分享机制是:a用户输入b用户的账号后就能把指定的设备分享给b用户，b用户登录帐号后可以拿到分享的设备.按照你们提供的逻辑可以做到吗，我试了不行

**Comment by blitzfeng** [comment]
可以的，b用户登录涂鸦账户体系后拿到shareId，调用接收分享，然后重新拉取设备列表getHomeDetail。如果有什么报错，反馈一下，提供shareId等一些信息帮你查询一下

**Comment by YY1989YY** [comment]
B用户怎么拿到shareId，服务器有返回吗

**Comment by blitzfeng** [comment]
A调用邀请接口拿到shareId，把shareId存到你们服务器，通过一些方式接口请求、推送之类的方式传给B用户
