### ISSUE TITLE
安卓增加定时不起作用问题

### ISSUE THREAD

**Issue by YY1989YY** [TuyaInc/tuyasmart_home_android_sdk#15]
集成tuyasmart_home_android_sdk（2.9.1），调用方法TuyaHomeSdk.getTimerManagerInstance().addTimerWithTask(）
所传参数：taskName:taskPlug,loops:1111111,devId:002003545ccf7f34a81e,dpId:{"1":true},time:09:35
结果：已尝试多次测试，绑定涂鸦的插座/排插（型号：F1501-GB/200B）后，增加定时器成功后没有起效果，设备没有在指定的时间进行对应关/开操作。

**Comment by YY1989YY** [comment]
刚刚测试，在排插是全开的状态下，对插孔1设置关闭的定时，时间为14:58
TuyaHomeSdk.getTimerManagerInstance().addTimerWithTask(TuyaConfig.TASK_NAME_PLUG, repeatTime, TuyaPlugHomeActivity?.deviceItem?.devId, dps, currentTime, object : IResultStatusCallback {
            override fun onSuccess() {}
            override fun onError(errorCode: String, errorMsg: String) { }
        })
参数如下：taskName:taskPlug,loops:1111111,devId:002003545ccf7f34a81e,dpId:{"1":false},time:14:58
反回的dp：{"1":false,"2":false,"3":false,"4":false,"5":true,"6":0}

**Comment by YY1989YY** [comment]
安卓系统集成tuyasmart-2.9.4版本的sdk，增加定时器后设备可以在指定的时间对应状态，但是编辑定时器（updateTimerWithTask(String taskName, String loops, String devId, String timerId, String dpId, String time, boolean isOpen, final IResultStatusCallback callback)）后返回的定时列表数据格式不统一，前端对数据解析不好把控，获取的定时列表数据如下
{"mTimerList":[{"mDate":"00000000","mDpId":"1","mLoops":"1111111","mStatus":0,"mTime":"10:35","mTimerId":"0000006c5r","mValue":"{\"1\":false}"},{"mDate":"00000000","mDpId":"{\"1\":false}","mLoops":"0111111","mStatus":1,"mTime":"11:17","mTimerId":"0000006c5m","mValue":"{\"{\\\"1\\\":false}\":true}"}],"mTimerTaskStatus":{"mIsOpen":true,"mTimerName":"IOTTuyaTimerTask"}}

**Comment by blitzfeng** [comment]
意思是说调用 addTimerWithTask 后调用定时列表的接口和 调用updateTimerWithTask 再调用定时列表接口，返回的数据格式不一样？具体哪个地方格式不一致？毕竟都是一个接口返回的数据

**Comment by YY1989YY** [comment]
上面提到的获取定时列表数据中mDpId和mValue两条数据格式不一致，前端需要解析这些数据获取需要的信息

**Comment by blitzfeng** [comment]
上面第二条数据是有问题的，这个是添加定时器或修改定时器传参错误导致的。比如updateTimerWithTask(String taskName, String loops, String devId, String timerId, String instruct,IResultStatusCallback callback)这个方法 参数instruct，正确的格式{“time": "20:00","dps": {"1": true}。
比如void addTimerWithTask(String taskName, String devId, String loops, Map<String, Object> dps, String time,IResultStatusCallback callback) 参数dps 的key是dp点，类似"1" 、"2"这种形式，value是dp点值可以boolean、raw等类型
第二条数据mValue 是把 {\"1\":false} 作为key，这种格式是错误的

**Comment by YY1989YY** [comment]
我按照官方文档来的，我再测试看看，谢谢

**Comment by YY1989YY** [comment]
按照你所说的，更新定时调用updateTimerWithTask方法，参数格式{"time":"17:16","dps":{"1":false}，返回的结果是：没法更新成功，服务器返回的远程调用失败。

**Comment by blitzfeng** [comment]
taskId提供一下

**Comment by YY1989YY** [comment]
更新定时的参数如下
updateTimerWithTask("IOTTuyaTimerTask", "1111111", "002003545ccf7f34a81e", "0000006dgw", String instruct,IResultStatusCallback callback)
instruct格式:{"time":"17:15","dps":{"1":false}

**Comment by blitzfeng** [comment]
不好意思，没描述清楚，我上面说的格式 {"time":"17:16","dps":{"1":false} 只写了一部分，主要想解释dps的正确的形式。完整的instruct格式是个json array，不是json object。比如正确的instruct 是[ {"time":"17:16","dps":{"1":false}],是一个数组形式

**Comment by YY1989YY** [comment]
好的，我再试试

**Comment by YY1989YY** [comment]
经过测试，已解决。谢谢，辛苦了
