### ISSUE TITLE
调用开始配网，抛异常

### ISSUE THREAD

**Issue by lepaitianshi** [TuyaInc/tuyasmart_home_android_sdk#16]
成功获取到配网Token后，配置好相关数据后，执行mTuyaActivator.start(); //抛异常
![image](https://user-images.githubusercontent.com/8243494/53721061-3b77b800-3e9d-11e9-9c6c-4d8e3717a45f.png)

**Comment by lepaitianshi** [comment]
`TuyaHomeSdk.getActivatorInstance().getActivatorToken(mHomeId, new ITuyaActivatorGetToken() {
                @Override
                public void onSuccess(String pS) {
                    LogUtils.i("Token:----->"+pS);
                    mActivatorBuilder=new ActivatorBuilder();
                    mActivatorBuilder.setSsid(WiFiUtil.getCurrentSSID(mContext));
                    mActivatorBuilder.setContext(mContext);
                    mActivatorBuilder.setPassword(strWifiPwd);
                    mActivatorBuilder.setActivatorModel(ActivatorModelEnum.TY_AP);
                    mActivatorBuilder.setTimeOut(100);
                    mActivatorBuilder.setToken(pS);
                    mActivatorBuilder.setListener(new ITuyaSmartActivatorListener() {
                        /**
                         *
                         * @param pS
                         * 1001        网络错误
                         * 1002        配网设备激活接口调用失败，接口调用不成功
                         * 1003        配网设备激活失败，设备找不到。
                         * 1004        token 获取失败
                         * 1005        设备没有上线
                         * 1006        配网超时
                         * @param pS1
                         */
                        @Override
                        public void onError(String pS, String pS1) {
                            ToastUtils.show(mContext,pS1);
                        }

                        @Override
                        public void onActiveSuccess(DeviceBean pDeviceBean) {
                            ToastUtils.show(mContext,"Success");
                            finish();
                        }

                        /**
                         *
                         * @param pS
                         * @param pO
                         */
                        @Override
                        public void onStep(String pS, Object pO) {
                            ToastUtils.show(mContext,"onStep");
                        }
                    });
                    mITuyaActivator=TuyaHomeSdk.getActivatorInstance().newMultiActivator(mActivatorBuilder);
                    mITuyaActivator.start();
                }

                @Override
                public void onFailure(String pS, String pS1) {

                }
            });`

**Comment by lepaitianshi** [comment]
`
TuyaHomeSdk.getActivatorInstance().getActivatorToken(mHomeId, new ITuyaActivatorGetToken() {
                @Override
                public void onSuccess(String pS) {
                    LogUtils.i("Token:----->"+pS);
                    mActivatorBuilder=new ActivatorBuilder();
                    mActivatorBuilder.setSsid(WiFiUtil.getCurrentSSID(mContext));
                    mActivatorBuilder.setContext(mContext);
                    mActivatorBuilder.setPassword(strWifiPwd);
                    mActivatorBuilder.setActivatorModel(ActivatorModelEnum.TY_AP);
                    mActivatorBuilder.setTimeOut(100);
                    mActivatorBuilder.setToken(pS);
                    mActivatorBuilder.setListener(new ITuyaSmartActivatorListener() {
                        /**
                         *
                         * @param pS
                         * 1001        网络错误
                         * 1002        配网设备激活接口调用失败，接口调用不成功
                         * 1003        配网设备激活失败，设备找不到。
                         * 1004        token 获取失败
                         * 1005        设备没有上线
                         * 1006        配网超时
                         * @param pS1
                         */
                        @Override
                        public void onError(String pS, String pS1) {
                            ToastUtils.show(mContext,pS1);
                        }

                        @Override
                        public void onActiveSuccess(DeviceBean pDeviceBean) {
                            ToastUtils.show(mContext,"Success");
                            finish();
                        }

                        /**
                         *
                         * @param pS
                         * @param pO
                         */
                        @Override
                        public void onStep(String pS, Object pO) {
                            ToastUtils.show(mContext,"onStep");
                        }
                    });
                    mITuyaActivator=TuyaHomeSdk.getActivatorInstance().newMultiActivator(mActivatorBuilder);
                    mITuyaActivator.start();
                }

                @Override
                public void onFailure(String pS, String pS1) {

                }
            });
`

**Comment by lepaitianshi** [comment]
`if (id == R.id.wifiConfirm) {
            strWifiPwd = wifiPwd.getText().toString();
            if (StringUtils.isEmpty(strWifiPwd)) {
                return;
            }
            TuyaHomeSdk.getActivatorInstance().getActivatorToken(mHomeId, new ITuyaActivatorGetToken() {
                @Override
                public void onSuccess(String pS) {
                    LogUtils.i("Token:----->"+pS);
                    mActivatorBuilder=new ActivatorBuilder();
                    mActivatorBuilder.setSsid(WiFiUtil.getCurrentSSID(mContext));
                    mActivatorBuilder.setContext(mContext);
                    mActivatorBuilder.setPassword(strWifiPwd);
                    mActivatorBuilder.setActivatorModel(ActivatorModelEnum.TY_AP);
                    mActivatorBuilder.setTimeOut(100);
                    mActivatorBuilder.setToken(pS);
                    mActivatorBuilder.setListener(new ITuyaSmartActivatorListener() {
                        /**
                         *
                         * @param pS
                         * 1001        网络错误
                         * 1002        配网设备激活接口调用失败，接口调用不成功
                         * 1003        配网设备激活失败，设备找不到。
                         * 1004        token 获取失败
                         * 1005        设备没有上线
                         * 1006        配网超时
                         * @param pS1
                         */
                        @Override
                        public void onError(String pS, String pS1) {
                            ToastUtils.show(mContext,pS1);
                        }

                        @Override
                        public void onActiveSuccess(DeviceBean pDeviceBean) {
                            ToastUtils.show(mContext,"Success");
                            finish();
                        }

                        /**
                         *
                         * @param pS
                         * @param pO
                         */
                        @Override
                        public void onStep(String pS, Object pO) {
                            ToastUtils.show(mContext,"onStep");
                        }
                    });
                    mITuyaActivator=TuyaHomeSdk.getActivatorInstance().newMultiActivator(mActivatorBuilder);
                    mITuyaActivator.start();
                }

                @Override
                public void onFailure(String pS, String pS1) {

                }
            });
        }`

**Comment by NextApp** [comment]
so架构问题，默认支持v7a架构，如果需要其他架构，可以从这里获取https://github.com/TuyaInc/tuyasmart_home_android_sdk/tree/master/so_libs

**Comment by lepaitianshi** [comment]
但是gradlew里面和Demo配置一样的啊，demo是可以运行

**Comment by lepaitianshi** [comment]
![image](https://user-images.githubusercontent.com/8243494/53784978-e2b62700-3f51-11e9-9ddb-0a4e69c4b18a.png)
![image](https://user-images.githubusercontent.com/8243494/53784985-ef3a7f80-3f51-11e9-84ba-b8c5af501472.png)

**Comment by lepaitianshi** [comment]
所有都加了，依然报错
