### ISSUE TITLE
FCM收不到消息

### ISSUE THREAD

**Issue by lukes-mips** [TuyaInc/tuyasmart_home_android_sdk#19]
配置了FCM, 在fcm后台发送的测试消息可以收到. 使用美国地区的账号, app收不到设备的告警消息

**Comment by mimimumu** [comment]
你有没有把google-service.json文件 senderid. serverkey  配置到涂鸦的平台呢

**Comment by mimimumu** [comment]
https://docs.tuya.com/cn/app/third-party/push/FCM-push.html

**Comment by lukes-mips** [comment]
> 你有没有把google-service.json文件 senderid. serverkey 配置到涂鸦的平台呢
这些都配置了

**Comment by mimimumu** [comment]
你可以提交一个工单给涂鸦，附上 应用名称，设备id。和测试账号。

**Comment by mimimumu** [comment]
https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/zh-hans/resource/Push.html

有没有按照文档，将fcm 获取的token ，注册到涂鸦云呢？


/**
* @param aliasId   用户别名 即fcm生成的token
* @param pushProvider   注册push的类别  fcm填"gcm"
*/        
TuyaHomeSdk.getInstance().registerDevice(String aliasId, String pushProvider, new IResultCallback() {
    @Override
    public void onError(String code, String error) {
    }

    @Override
    public void onSuccess() {

    }
});

**Comment by lukes-mips** [comment]
重新配置了一下, 可以收到了
