### ISSUE TITLE
设备类型

### ISSUE THREAD

**Issue by lepaitianshi** [TuyaInc/tuyasmart_home_android_sdk#20]
我要区分设备类型，刚开始以为是截图的字段，但是发现窗帘和开关的类别是相同的，所有设备类型code有哪些？从哪里取值？截图内容为DeviceBean的数据
![image](https://user-images.githubusercontent.com/8243494/53797804-ee194a80-3f71-11e9-914b-ddb2b1788443.png)

![image](https://user-images.githubusercontent.com/8243494/53797829-f83b4900-3f71-11e9-8d4e-d5ac02506f87.png)

**Comment by NextApp** [comment]
现在区分设备类型只能用ProductId
