### ISSUE TITLE
场景创建问题

### ISSUE THREAD

**Issue by RedSun001** [TuyaInc/tuyasmart_home_android_sdk#27]
![屏幕快照 2019-04-01 上午9 55 34](https://user-images.githubusercontent.com/16470623/55299446-9c2aee00-5465-11e9-8da9-c15331eba5f7.png)
以上是我的代码。另外public void createScene(long homeId, String name, String background,
  最后一个参数String background文档没有说明，麻烦提供一下指导，谢谢

**Comment by RedSun001** [comment]
SdcSceneManager.getInstance().createScene（）方法返回error如下图
![屏幕快照 2019-03-29 下午6 20 12](https://user-images.githubusercontent.com/16470623/55300114-a8fd1100-5468-11e9-8162-81aeca2c2300.png)

**Comment by nielev** [comment]
sdk文档里对背景图片的获取进行了更新，你可以用下面的方法获取到场景background的url列表
TuyaHomeSdk.getSceneManagerInstance().getSceneBgs(newITuyaResultCallback<ArrayList<String>>() {
        @Override
        public void onSuccess(ArrayList<String> strings) {

        }

        @Override
        public void onError(String s, String s1) {

        }
    });

**Comment by RedSun001** [comment]
您好  SDK中找不到TuyaHomeSdk.getSceneManagerInstance().getSceneBgs（）这个方法，请问SDK更新了吗？

**Comment by RedSun001** [comment]
您好  SDK中找不到TuyaHomeSdk.getSceneManagerInstance().getSceneBgs（）这个方法，请问SDK更新了吗？

**Comment by nielev** [comment]
请问您的sdk版本是3.0.0吗，我们文档和sdk前段时间刚刚更新
implementation 'com.tuya.smart:tuyasmart:3.0.0'

**Comment by RedSun001** [comment]
刚刚更新了。更新完发现登陆不上去了。。。
![屏幕快照 2019-04-01 下午7 21 57](https://user-images.githubusercontent.com/16470623/55324064-88a67400-54b3-11e9-8535-bf179520b0c2.png)
错误log打印SING_VALIDATE_FALED权限校验失败

**Comment by RedSun001** [comment]
![屏幕快照 2019-04-01 下午7 21 57](https://user-images.githubusercontent.com/16470623/55324293-2d28b600-54b4-11e9-8aea-9ae2dbf49f30.png)

登陆代码

**Comment by nielev** [comment]
我们新版本sdk方式发生了变更，需要发起一个工单提交到我们IOT平台，https://iot.tuya.com/council/ticket/create,工单里的填写应用名称，包名，
然后把工单的id发给我们，我们给您快速处理一下

**Comment by nielev** [comment]
https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/zh-hans/resource/Preparation.html
新的集成方式我们的文档也更新了
