### ISSUE TITLE
新建房间名字查重问题

### ISSUE THREAD

**Issue by RedSun001** [TuyaInc/tuyasmart_home_android_sdk#29]
您好，请问涂鸦云是否做了同一家庭下房间名称查重，我们这边测试新建相同房间名称的操作是可以的。麻烦涂鸦提供一下指导，谢谢。

**Comment by chainsaw** [comment]
抱歉，这边是Android仓库，对外统一处理Android相关问题。关于重名部分客户端SDK是不做限制的
