### ISSUE TITLE
绑定ZIGBEE网关超时

### ISSUE THREAD

**Issue by KnightSch** [TuyaInc/tuyasmart_home_android_sdk#31]
我们使用sdk的步骤如下：
1, TuyaHomeSdk.init();
2, TuyaHomeSdk.getUserInstance().loginWithPhonePassword();
3, TuyaHomeSdk.getHomeManagerInstance().createHome();
4, TuyaHomeSdk.getActivatorInstance().getActivatorToken();
5, TuyaHomeSdk.getActivatorInstance().newGwActivator().start();
 绑定结果：cfgGwProcess [ 1006 ], errMsg: time out;
对比使用官方app可以正常绑定网关，现在抓取了一下日志，烦请帮忙分析，谢谢！
[appSdkLog.txt](https://github.com/TuyaInc/tuyasmart_home_android_sdk/files/3071813/appSdkLog.txt)

**Comment by NextApp** [comment]
TuyaHomeSdk.init 一定要在application onCreate里面，不然会造成配网异常

**Comment by KnightSch** [comment]
谢谢，TuyaHomeSdk.init 放在application onCreate里绑定成功！
