### ISSUE TITLE
how to change uid passwords

### ISSUE THREAD

**Issue by rndtester** [TuyaInc/tuyasmart_home_android_sdk#33]
Hi,

How can we change password using UID login system?

Gary told me that we should registered the same email but different password and it will override the old account. But it didn't work. 

Thanks!

**Comment by mimimumu** [comment]
https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/en/resource/User_uid.html#3-reset-user-uid-password

Hello, please refer to the documentation.。
The user uid password resetting requires Cloud-Cloud connection. Please refer to the Cloud API documents for details.
