### ISSUE TITLE
无法绑定ZigBee网关

### ISSUE THREAD

**Issue by YY1989YY** [TuyaInc/tuyasmart_home_android_sdk#34]
SDK版本号：tuyasmart-2.9.4
按照官网文档ZigBee设备配网流程无法绑定网关设备，绑定超时，ITuyaSmartActivatorListener监听里面的三个方法都没有调用

**Comment by NextApp** [comment]
建议使用3.0.0版本的SDK

**Comment by YY1989YY** [comment]
3.0.0的版本官网可以下载吗，这个版本uuid分享功能和定时功能都是稳定的吧

**Comment by YY1989YY** [comment]
我试了3.0.0版本，不支持uuid分享设备，登入都没法登入，返回code:SING_VALIDATE_FALED,error:权限校验失败

**Comment by NextApp** [comment]
权限校验失败是因为3.0.0使用加密图片方案，需要重新更换key和appsecret，还有安全图片
