### ISSUE TITLE
android app registration failed

### ISSUE THREAD

**Issue by 4naveen** [TuyaInc/tuyasmart_home_android_sdk#36]
Hi ,
I am trying to register through app then i am getting this issue.can you please check this issue

{"t":1557739068368,"success":false,"errorCode":"SING_VALIDATE_FALED_4","status":"error","errorMsg":"sign validate failed 4"}

**Comment by NextApp** [comment]
you need get the new appkey and appsecret and security img , replace the old.

**Comment by 4naveen** [comment]
Yes , I added new appkey and secret key and please let me know where I have
image file
In project

Regards
Naveen Kumar

**Comment by NextApp** [comment]
you can get it in the Tuya IOT platform. https://iot.tuya.com/index

**Comment by aminovicnouri** [comment]
same problem, i didn't found a solution
