### ISSUE TITLE
如何给单个设备和群组添加普通定时，随机定时，循环定时

### ISSUE THREAD

**Issue by Lee-Jian** [TuyaInc/tuyasmart_home_android_sdk#37]
如何给单个设备和群组添加普通定时，随机定时，循环定时，用哪个API

**Comment by blitzfeng** [comment]
https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/zh-hans/resource/Timer.html  
void addTimerWithTask(String taskName, String loops, String devId, String dpId, String time, final IResultStatusCallback callback); 看下文档通过设置loops 可以设置只执行1次定时或者循环定时。不明白你所说的随机定时是什么意思

**Comment by Lee-Jian** [comment]
随机定时：//大于 1h，在开始后 2-30 分钟内执行，直到关闭前 2-30 分钟内停止 //例如:定时 8:00--10:00，则 随机时间为 8:02-8:30 开，9:30-9:58 关
/小于 1h，在开始后 2-x 分钟内执行，直到关闭前 2-x 分钟内停止, x=间隔时间/2-2 //例如:定时任 务是 8:00-8:30;随机开启时;开的时间点是 8:02——8:13;关的时间是 8:17-8:28
//小于 1h，在开始后 2-x 分钟内执行，直到关闭前 2-x 分钟内停止, x=间隔时间/2 //例如:定时任务 是 8:00-8:30;随机开启时;开的时间点是 8:02——8:13;关的时间是 8:17-8:28

**Comment by blitzfeng** [comment]
目前不支持随机定时
