### ISSUE TITLE
关于场景创建执行和切换的问题

### ISSUE THREAD

**Issue by RedSun001** [TuyaInc/tuyasmart_home_android_sdk#38]
您好麻烦指导一下以下问题，谢谢！

1、public void createScene(long homeId, String name, String background。。。）创建场景的background参数是什么意思，创建不同的场景需要特定的background还是任意一个就行。
2、执行一个场景后如何停止此场景？SDK中只有一个删除场景，是否使用删除场景来停止本场景。
3、不同场景间切换如何实现？是否需要先删除上一个再创建执行下一个

**Comment by nielev** [comment]
1、background是场景的背景图片url地址，sdk中有获取场景背景的方法getBgs()可以获取背景图片链接地址，详见sdk文档。
2、场景分别自动化场景和手动执行场景，自动化场景拥有条件condition,满足条件即可触发，可以通过sdk方法disableScene和enableScene停止和启用自动化。而手动场景则是不包含condition条件参数，需要通过sdk方法executeScene去执行，且只会执行一次。
3、场景的切换需要业务方自己实现，可以参考我们的app涂鸦智能或者智能生活
