### ISSUE TITLE
部分手机无法AP配网，连上设备热点后再返回app不会自动跳转， 关闭4G网络，正常配网

### ISSUE THREAD

**Issue by xionghai123** [TuyaInc/tuyasmart_home_android_sdk#39]
问题：
模块处于station+AP模式，手机连接上模块，模组日志显示手机连接，并显示MAC地址，手机也显示连接上smart热点
该华为手机（当前只发现一部mate10）连上这个芯片设备的热点后，发广播包就自动选择了4G网卡，而连其他的设备就选择的是连接的设备的热点WiFi网卡
当前解决方案：
app使用绑定wlan 网卡的方式发送配网广播包

**Comment by NextApp** [comment]
fixed with 3.9.6
