### ISSUE TITLE
can anyone please explain what is here three class level variables i.e p2pid,p2pwd and local key

### ISSUE THREAD

**Issue by 4naveen** [TuyaInc/tuyasmart_home_android_sdk#4]
![screenshot 46](https://user-images.githubusercontent.com/24203901/51535005-5520eb00-1e6d-11e9-9992-f79e01817e53.png)

**Comment by Tuya-DJ** [comment]
P2pconnect should be validated by p2pid, p2pwd and localkey

**Comment by 4naveen** [comment]
sorry,I didn't understand can you explain how  is process is working with code in screenshot

I have a smart doorbell device and I created one app by following this documentation in the url  
https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/en/resource/Device.html
 and through my i can register device and get registered device using sdk ,now i want to fetch live stream video from doobel camera into my app

**Comment by Tuya-DJ** [comment]
https://gitlab.com/TuyaSmartCamera/tuyasmart_camera_android_sdk/blob/release/v3.0.0/TUYA_CameraSDK_English.md
