### ISSUE TITLE
category getting as null value Please check below code

### ISSUE THREAD

**Issue by 4naveen** [TuyaInc/tuyasmart_home_android_sdk#40]
mDevListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                DeviceBean bean = beanDevices.get(position);
                Log.e("device_id", bean.devId);
                Log.e("device_idxx", bean.getDevId());
                Log.e("local_key", bean.getLocalKey());
                Log.e("category", bean.getCategory());
                final String local_key = bean.getLocalKey();
                final String device_id = bean.getDevId();
                Map<String, Object> map = new HashMap<>();
                map.put("devId", bean.devId);
                Map<String, Object> map1 = bean.getSkills();
                int p2pType = -1;
                if (map1 == null || map1.size() == 0) {
                    p2pType = -1;
                } else {
                    p2pType = (Integer) (map1.get("p2pType"));
                }

                final int finalP2pType = p2pType;

                TuyaHomeSdk.getRequestInstance().requestWithApiName("tuya.m.ipc.config.get", "1.0", map, new IRequestCallback() {
                    @Override
                    public void onSuccess(Object o) {
                       // Log.e("response", o.toString());
                        String json_str = o.toString();
                        Gson g = new Gson();
                        Result result = g.fromJson(json_str, Result.class);

                        Log.e("initStr", result.getP2pConfig().getInitStr() + "p2pkey" + result.getP2pConfig().getP2pKey()+"category"+result.getCategory());

                        gotoDeviceControlActivity(finalP2pType, device_id, result.getP2pId(), local_key, result.getPassword(), result.getP2pConfig().getInitStr(), result.getP2pConfig().getP2pKey());

                    }

                    @Override
                    public void onFailure(String s, String s1) {

                    }
                });

                //  mDeviceListFragmentPresenter.onDeviceClick((DeviceBean) parent.getAdapter().getItem(position));

                //gotoDeviceControlActivity(bean.getDevId(),bean.getLocalKey());

            }
        });

**Comment by NextApp** [comment]
pls replace with this: deviceBean.getProductBean().getCategory()
