### ISSUE TITLE
How to send custom colour?

### ISSUE THREAD

**Issue by Hututu2019** [TuyaInc/tuyasmart_home_android_sdk#41]
"ankit: dps = @{@"4": @"ff5500"};"
- - - - - - - - - - - - - - -
is this the correct dps to send custom colour??

**Comment by ankit776** [comment]
i also tried with some other dps dictionary
dps = @{ @"102" : @"ff5500" };
dps = @{ @"2" : @"ff5500" };
i also try with multiple commands shows in your document
dps = @{@"1": @(YES), @"4": @(ff5500)};

always get data type error.
document link:-
https://docs.tuya.com/en/app/app-sdk/ios-sdk.html#device-control

**Comment by ankit776** [comment]
in Android
as per your doc we follow this *(/ / Set the dpId to 4 string type function point example role: set the RGB color to ff5500 
dps = {"4": "ff5500"};)* 

in android we get success but color not reflected on devices

**Comment by NextApp** [comment]
you need to get the device control doc.
