### ISSUE TITLE
Registration Failed (Permission Validation Failed)

### ISSUE THREAD

**Issue by gulamyakkaspace** [TuyaInc/tuyasmart_home_android_sdk#42]
Hi,
 I used the demo app, I can not register in the app. 
**I received following error :**
Business api: tuya.p.time.get {"t":1559304354808,"success":false,"errorCode":"SING_VALIDATE_FALED","status":"error","errorMsg":"Permission validation failed"}

**Comment by NextApp** [comment]
hi , you need to get the security image . refer to this https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/en/resource/Integrated.html
