### ISSUE TITLE
Android 定时的dpId是什么意思，有什么规则吗

### ISSUE THREAD

**Issue by Lee-Jian** [TuyaInc/tuyasmart_home_android_sdk#43]
Android 智能插座 定时。给设备定时的接口是void addTimerWithTask(String taskName, String devId, String loops, Map<String, Object> dps, String time, final IResultStatusCallback callback);其中 参数 @param dps    dp点键值对，key是dpId，value是dpValue,仅支持单dp点。 ----------- 但我不明白其中的dpId是什么。传dpId的规则是什么。

**Comment by blitzfeng** [comment]
dpId是dp点的id，dp点是设备的功能点，举个例子，单插，只有一个dp点，就是控制设备的开关，一个完整的dp点是{"1":true}, 其中1是dpId，true是dp value。设备有可能有多个dp点，取决于设备，一般来说，dpId只能是字符串类型的数字。
