### ISSUE TITLE
Android 智能插座 定时

### ISSUE THREAD

**Issue by Lee-Jian** [TuyaInc/tuyasmart_home_android_sdk#44]
目前定时插座，根据void addTimerWithTask(String taskName, String devId, String loops, Map<String, Object> dps, String time, final IResultStatusCallback callback);这个接口，我们可以设置设备定时开或者定时关。如果我想配成时间段的定时开和关，例如我想让它10:00开，11：23关，该如何处理？

**Comment by blitzfeng** [comment]
添加定时器的接口只能执行单dp点的定时任务，10:00开，11：23关只能添加两个定时器
