### ISSUE TITLE
SDK开发的APP群组添加设备问题

### ISSUE THREAD

**Issue by Hututu2019** [TuyaInc/tuyasmart_home_android_sdk#45]
客户现在的产品，用涂鸦的APP可以添加群组，但是用他们自己的不行。他们的APP在添加群组时会显示：“No implementation found for void com.tuya.smart.android.device.TuyaSmartLink.sendStatusStop()”
代码是：{8=ffff8003ff000000ff000000ff000000000000000000, 1=true, 10=ffff0505ff000000ff00ffff00ff00ff0000ff000000, 6=00ff0000000000, 7=ffff500100ff00, 5=1200ff00f4115d, 9=ffff5001ff0000, 11=, 3=200, 2=colour}
怎么解呢？

**Comment by NextApp** [comment]
可以提供详细的日志信息吗？

**Comment by Hututu2019** [comment]
> 可以提供详细的日志信息吗？
2019-06-14 11:30:50.779 11646-11760/com.jaquarlighting.jaquarlighting I/
Tuya: TuyaApiSignManager Request.generateSignature: a=s.m.dev.group.add||appVersion=0.6||clientId=8fmdhm5cpqvfjanvedku||deviceId=de2de8bc6e17b3e475d8617169cd652823d599fc3254||imei=56512SM-J715f20||imsi=56523SM-J715ef7||lang=en||os=Android||postData=4bb7a25f5d18e63edb430df56c730eea||sid=eu155833G63136951KIgj2Y39522baf44b82cd5d058009b314d60349||time=1560492051||ttid=android||v=1.0||e3mvdshurhw8cm595n9qq7m88fahekaq =>MD5: 8f291cc362e5744c4197c1d3d5ab2d34
-->errorCode: PERMISSION_DENIED | errorMsg: No permissions

**Comment by NextApp** [comment]
设备id能发一下吗？这个设备有开通群组这个能力吗？
