### ISSUE TITLE
sdk 升级

### ISSUE THREAD

**Issue by Lee-Jian** [TuyaInc/tuyasmart_home_android_sdk#46]
目前  implementation 'com.tuya.smart:tuyasmart:2.9.3'
如何更新到3.9.6版,中间可能造成什么影响

**Comment by NextApp** [comment]
1、需要联系我们后台客服人员升级把OEM应用升级为SDK应用。（可以提工单）。

**Comment by NextApp** [comment]
1、需要联系我们后台客服人员升级把OEM应用升级为SDK应用。（可以提工单）。
2、替换appkey和appsecret 并升级安全图片，参考文档说明：
https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/zh-hans/resource/Preparation.html
https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/zh-hans/resource/Integrated.html
3、替换arm64位so库https://github.com/TuyaInc/tuyasmart_home_android_sdk/tree/master/so_libs/3.9.6
