### ISSUE TITLE
Bug in getReceivedShareInfo

### ISSUE THREAD

**Issue by MimikFc7** [TuyaInc/tuyasmart_home_android_sdk#47]
Hello, check please some bug in your sdk.
and add please one field in shared details instace
bug:
when i call 
```
TuyaHomeSdk.getDeviceShareInstance().getReceivedShareInfo(user.getMemeberId(), new ITuyaResultCallback<ShareReceivedUserDetailBean>() 
 public void onSuccess(ShareReceivedUserDetailBean shareReceivedUserDetailBean) 

```
in shareReceivedUserDetailBean i have not correct data
in field 
mobile i see homename but must be a user phone or email
nameWithoutRemark - return as null

and please add field in 
ShareReceivedUserDetailBean
ShareSentUserDetailBean

a field memberId - userid for identification owners devces

best regards Mimik

**Comment by SanfenR** [comment]
in SDK_3.0+, shared devices come from family, that not about the user, so ShareReceivedUserDetailBean and ShareSentUserDetailBean have only homename

**Comment by MimikFc7** [comment]
Hellom thanx for answer, but that is no good, and are you shure about ShareSentUserDetailBean ?
in that class when i call him, i see a user login, and than is correct because in class haved fields and options for get Phone and Login not field homename field has name phone, please fix that, this is very help for quickly coding and minimize code for list user inforamtions and device list sharing.

**Comment by SanfenR** [comment]
in SDK_2.0， ShareSentUserDetailBean has user information who shared the devices，but 3.0, devices are Shared only by families. We are considering upgrading from 2.0 to 3.0，so the name and parameters of this class are not changed，which caused misunderstanding. We're going to look at optimization.

**Comment by MimikFc7** [comment]
Hello, plese return phone or add field memberId, i want show a user list vith list devices shared and recieved, and in sdk last   implementation 'com.tuya.smart:tuyasmart:3.9.6'
in ShareSentUserDetailBean - haved a login user
in ShareReceivedUserDetailBean - home name
that is really strong, if are you add memberId or login back, this is make me happy and remove 100 linec code and two threads in my application
