### ISSUE TITLE
Android提示权限校验失败 

### ISSUE THREAD

**Issue by Eafy** [TuyaInc/tuyasmart_home_android_sdk#53]
提示：涂鸦登录失败[SING_VALIDATE_FALED_4]:权限校验失败4
请问是什么系统权限还是什么权限？

**Comment by NextApp** [comment]
这个错误是appkey和appsecret或者安全图片配置错误导致的，升级3系列的时候，需要替换appkey和appsecret 还有安全图片

**Comment by Lee-Jian** [comment]
是把原来App工作平台上的App sdk删除再重新获取SDk，配置包名，获取sdk吗，这对以前上线版本有影响吗

**Comment by Lee-Jian** [comment]
@NextApp

**Comment by Eafy** [comment]
请问下安全图片，Debug和Release的图片是一样的吗？还是有区分？

**Comment by Eafy** [comment]
同时验证用2.7.5.aar的包会出现校验失败，用导包方式的3.9.6 API没有问题，这个是需要升级SDK还是？

**Comment by NextApp** [comment]
@Lee-Jian 如果是存在老版本，可以联系运营把OEM应用转成SDK应用

**Comment by NextApp** [comment]
@Eafy Debug和release图片是不一样的，debug包用debug图片，release包用release图片，升级了3系列SDK，就无法降回去测试了。

**Comment by Eafy** [comment]
请问下有对外的Q群吗？我在用Panel-0.0.9的时候，用Smart-2.7.5出现校验不成功，用Smart-3.9.6校验OK，但是Panel里会出现闪退，应该是部分API不兼容3系列，请问下Panel又新的版本吗？

**Comment by Eafy** [comment]
<img width="1132" alt="图片" src="https://user-images.githubusercontent.com/12604160/60406881-c453f580-9bea-11e9-8bc7-880d245007a3.png">

**Comment by NextApp** [comment]
panel有新的版本了

**Comment by yueshituya** [comment]
对应的panel 仓库develop分支有了更新的版本

**Comment by xixixx** [comment]
> 这个错误是appkey和appsecret或者安全图片配置错误导致的，升级3系列的时候，需要替换appkey和appsecret 还有安全图片

请问，生成的这个三个可以直接拿涂鸦账号来登陆吗
