### ISSUE TITLE
升级3系列的时候登录涂鸦不成功

### ISSUE THREAD

**Issue by Lee-Jian** [TuyaInc/tuyasmart_home_android_sdk#54]
由2.9.3升级3系列的时候，根据uid登录涂鸦，走错误回调，回调参数的值为USER_PASSWD_WRONG，账号或密码错误！
这是由什么原因产生的，该如何解决

 TuyaHomeSdk.getUserInstance().loginWithUid(countryCode, uid, passwd, new ILoginCallback() {
            @Override
            public void onSuccess(User user) {
                if (user != null) {
                    LogUtil.d("-->> SignInPresenterImpl loginTuyaAccount onSuccess user name=" + user.getNickName() + " uid=" + user.getUid());
                  
                    if (user.getHeadPic() != null && user.getHeadPic().length() > 0) {
                        globalPrefs.setmTuyaPhoto(user.getHeadPic());
                    }
                    if (signInView != null) {
                        signInView.notifySignInResult(ConstantValue.SUCCESS);
                    }
                }
            }

            @Override
            public void onError(String s, String s1) {
                  LogUtil.d("-->> SignInPresenterImpl loginTuyaAccount onError code=" + s + " error=" + s1);
                if (signInView != null) {
                    signInView.notifySignInResult(String.valueOf(ConstantValue.API_REQUEST_ERROR_CODE));
                }
                logout();
            }
        });
    }

**Comment by Lee-Jian** [comment]
升级的时候后台需要做什么吗

**Comment by NextApp** [comment]
如果是从老应用升级到新应用，需要提工单联系运营，把OEM应用转成SDK应用
