### ISSUE TITLE
android camera exception

### ISSUE THREAD

**Issue by MimikFc7** [TuyaInc/tuyasmart_home_android_sdk#59]
google require 64bit libs, when add 'arm64-v8a' and add libs, camera libs tuyaCamera-3.0.3.aar sdk libs 'com.tuya.smart:tuyasmart:3.9.6'
have exception:
No implementation found for void com.tutk.IOTC.IOTCAPIs.IOTC_Setup_Session_Alive_Timeout(int) (tried Java_com_tutk_IOTC_IOTCAPIs_IOTC_1Setup_1Session_1Alive_1Timeout and Java_com_tutk_IOTC_IOTCAPIs_IOTC_1Setup_1Session_1Alive_1Timeout__I)
 Shutting down VM
FATAL EXCEPTION: main
        java.lang.UnsatisfiedLinkError: No implementation found for void com.tutk.IOTC.IOTCAPIs.IOTC_Setup_Session_Alive_Timeout(int) (tried Java_com_tutk_IOTC_IOTCAPIs_IOTC_1Setup_1Session_1Alive_1Timeout and Java_com_tutk_IOTC_IOTCAPIs_IOTC_1Setup_1Session_1Alive_1Timeout__I)
        at com.tutk.IOTC.IOTCAPIs.IOTC_Setup_Session_Alive_Timeout(Native Method)`

**Comment by Tuya-DJ** [comment]
implementation "com.tuya.smart:tuyaCamera:3.0.6"

**Comment by Tuya-DJ** [comment]
https://github.com/TuyaInc/tuyasmart_camera_android_sdk/tree/release/3.0.6

**Comment by Tuya-DJ** [comment]
please have a try

**Comment by MimikFc7** [comment]
Hello, thanx! Maybe you can help me and with share bugs ? that ticket:
[https://github.com/TuyaInc/tuyasmart_home_android_sdk/issues/52](url)

**Comment by MimikFc7** [comment]
> https://github.com/TuyaInc/tuyasmart_camera_android_sdk/tree/release/3.0.6
Sorry but that is does not help =(

No implementation found for void com.tutk.IOTC.IOTCAPIs.IOTC_Setup_Session_Alive_Timeout(int) (tried Java_com_tutk_IOTC_IOTCAPIs_IOTC_1Setup_1Session_1Alive_1Timeout and Java_com_tutk_IOTC_IOTCAPIs_IOTC_1Setup_1Session_1Alive_1Timeout__I)

**Comment by Tuya-DJ** [comment]
please have a try implementation "com.tuya.smart:tuyaCamera:3.0.8"
Equipment firmware is too old，can you upgrade it ?

**Comment by MimikFc7** [comment]
> please have a try implementation "com.tuya.smart:tuyaCamera:3.0.8"
> Equipment firmware is too old，can you upgrade it ?

that lib not have excepton, but don't have a video stream from camera!

**Comment by MimikFc7** [comment]
One more excteption in library  tuyasmart 3.9.6
java.lang.ClassNotFoundException: com.tuya.sdk.log.LogPlugin
W/System.err:     at java.lang.Class.classForName(Native Method)
W/System.err:     at java.lang.Class.forName(Class.java:453)
W/System.err:     at java.lang.Class.forName(Class.java:378)

**Comment by Tuya-DJ** [comment]
please use tuyasmart 3.11.0 library
and upgrade camera firmware

**Comment by MimikFc7** [comment]
> please use tuyasmart 3.11.0 library
> and upgrade camera firmware

Seriously? Update camera firmware?
The camera is 100 kilometers from me, how will I update it?

**Comment by Tuya-DJ** [comment]
it is suggesstion. This type of device firmware can not be well supported to the app camera SDK. can you get your contacts to help you upgrade?

**Comment by MimikFc7** [comment]
> it is suggesstion. This type of device firmware can not be well supported to the app camera SDK. can you get your contacts to help you upgrade?

Yes i have email IgorSmt@rambler.ru
