### ISSUE TITLE
camera exceptions

### ISSUE THREAD

**Issue by MimikFc7** [TuyaInc/tuyasmart_home_android_sdk#60]
Hello! Really all your sdk does not work with camera!

```
com.tuya.smart.camera.ipccamerasdk.p2p.ICameraP2P camera11 = TuyaSmartCameraP2PFactory.generateTuyaSmartCamera(1);
```
camera11 - is null

`camera = TuyaSmartCameraFactory.generateTuyaSmartCamera(1);`
camera - is null 

 implementation "com.tuya.smart:tuyaCamera:3.11.0r119h2"
 implementation 'com.tuya.smart:tuyasmart:3.11.0'
 implementation 'com.tuya.smart:tuyasmart-ipc-camera-middleware:3.11.1r119'
 implementation 'com.tuya.smart:tuyasmart-ipc-camera-v2:3.11.0r119'
 implementation 'com.tuya.smart:tuyasmart-ipc-camera-utils:3.11.0r119'

if try

TuyaHomeSdk.getRequestInstance().requestWithApiName("tuya.m.ipc.config.get", "2.0",postData,new IRequestCallback()

infoBean.getP2pConfig().getIces() - exception
infoBean.getP2pConfig() is null

**Comment by MimikFc7** [comment]
Hello tuya 
While are you not want help a your users. i found your bug when camera not working


i create surface viewer end create camera
com.tutk.IOTC.Camera test_camera = new com.tutk.IOTC.Camera(); // yes i now that not yours =)
next atach camera
monitor.attachCamera(test_camera, 0);


monitor - it's a MediaCodecMonitor (hello TUTK)
next connect   
test_camera.connect(infoBean.getString("p2pId"));

and finish:

test_camera.start(0, "admin","this is a password"); // yes i found him, i decompile your sources and dasm libs 

camera.startShow(0,true,false,false); - so that is bug! view normally working only that

whei i set camera.startShow(0,false,false,false);  //first argument - it's a isRunSoft - if i correct understood  then video will not show. 

so i hope you correct that and give normaly library!

Best regards, Mimik

**Comment by Tuya-DJ** [comment]
hi, can you support your device ID?

**Comment by MimikFc7** [comment]
> hi, can you support your device ID?

not now, i come to home in 19-00 msk and give

but i think in your sdk camera.startShow(0,true,false,false);  
your not correct enable software/hardware decoder

i forget tell ^ that is work in sdk smartcamera 3.0.8

**Comment by Tuya-DJ** [comment]
i know, The latest SDK has changed a lot. The firmware of the old equipment is no longer support. your camera firmware is too old.
That's the reason for the problem.

**Comment by MimikFc7** [comment]
> i know, The latest SDK has changed a lot. The firmware of the old equipment is no longer support. your camera firmware is too old.
> That's the reason for the problem.

I install your example app, include my app key and sec code add t_s.bmp
open my camera, tap in "check firmware update" - ask me "no firmware update" 

we are sold many your's cameras,really update all - so strong task

**Comment by MimikFc7** [comment]
> i know, The latest SDK has changed a lot. The firmware of the old equipment is no longer support. your camera firmware is too old.
> That's the reason for the problem.

tell me, why i initialize a  **com.tutk.IOTC.Camera test_camera**  and can see a video stream ?

**com.tutk.IOTC.Camera** - included in your sdk. not other libs, only yours

**Comment by Tuya-DJ** [comment]
in the last sdk , we can`t support com.tutk.IOTC.Camera

**Comment by MimikFc7** [comment]
> > i know, The latest SDK has changed a lot. The firmware of the old equipment is no longer support. your camera firmware is too old.
> > That's the reason for the problem.
> 
> I install your example app, include my app key and sec code add t_s.bmp
> open my camera, tap in "check firmware update" - ask me "no firmware update"
> 
> we are sold many your's cameras,really update all - so strong task

and in your example camera not show a video too

**Comment by Tuya-DJ** [comment]
3.11.0 sdk, we would not support com.tutk.IOTC.Camera.

**Comment by MimikFc7** [comment]
> in the last sdk , we can`t support com.tutk.IOTC.Camera

so, if you use a tutk sdk, why not correct a support for old devices?  if you use that, or you change full provider?

you full remove a tutk support?

**Comment by Tuya-DJ** [comment]
3.11.0 sdk, we would not support com.tutk.IOTC.Camera.

**Comment by MimikFc7** [comment]
i forget, i make a info popup in app, my device id for camera: **bf9b1a74420f82893f6ca5**

**Comment by MimikFc7** [comment]
> 3.11.0 sdk, we would not support com.tutk.IOTC.Camera.

tell me why 

TuyaSmartCameraP2PFactory.generateTuyaSmartCamera(1); - is null
and
TuyaSmartCameraFactory.generateTuyaSmartCamera(1); - is null 

in last sdk 3.11*

**Comment by Tuya-DJ** [comment]
1 is tutk

**Comment by Tuya-DJ** [comment]
Your equipment, I've arranged for my colleagues to upgrade.
please wait

**Comment by Tuya-DJ** [comment]
ota is ready，please try it

**Comment by MimikFc7** [comment]
Thanks only evening i can check, but now com.tutk.IOTC.Camera - is worked
if i check and all normally work, you can get for me instrument for update all my cameras?

**Comment by Tuya-DJ** [comment]
Please contact the staff who are in contact with us. then we will upgrade all your cameras

**Comment by MimikFc7** [comment]
> Please contact the staff who are in contact with us. then we will upgrade all your cameras

nope =(

 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.tuya.smart.camera.tuyadeleagte.ICameraP2P.registorTuyaCameraListener(com.tuya.smart.camera.tuyadeleagte.OnDelegateCameraListener)' on a null object reference
        at com.tuya.smart.camera.middleware.TuyaCamera.registorOnDelegateCameraListener(TuyaCamera.java:41)

**Comment by MimikFc7** [comment]
> > Please contact the staff who are in contact with us. then we will upgrade all your cameras
> 
> nope =(
> 
> Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.tuya.smart.camera.tuyadeleagte.ICameraP2P.registorTuyaCameraListener(com.tuya.smart.camera.tuyadeleagte.OnDelegateCameraListener)' on a null object reference
> at com.tuya.smart.camera.middleware.TuyaCamera.registorOnDelegateCameraListener(TuyaCamera.java:41)

  camera = TuyaSmartCameraFactory.generateTuyaSmartCamera(2);
        camera.registorOnDelegateCameraListener(this);

**Comment by MimikFc7** [comment]
java.lang.ClassNotFoundException: com.tuya.sdk.log.LogPlugin - to last sdk other not identify exception =)

**Comment by Tuya-DJ** [comment]
1. upgrade your device，https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/en/resource/OTA.html
2. try to connect camera with sdk api

**Comment by MimikFc7** [comment]
update camera,  VerSw 2.7.0
try sdk 3.0.8
D/Tuya: TuyaSmartHardwareManager online: true; devId: bf9b1a74420f82893f6ca5
D/Tuya: TuyaSmartHardwareManager add new gw
D/Tuya: LocalControlModel queryDp: {}
D/Tuya: TuyaHardwareManager {}
D/Tuya: LocalControlNormal localControlNormal
D/Tuya: DeviceEventSender devUpdate
D/Tuya: TuyaDeviceMonitorManager devId: bf9b1a74420f82893f6ca5 online:true
D/Tuya: GwTransferModel hardware control success
D/Tuya: GwTransferModel response devId:bf9b1a74420f82893f6ca5;version: 3.2;data:21;type:16;code:1; time=1566510679901
E/Tuya: TuyaSmartHardwareManager local control devId:bf9b1a74420f82893f6ca5 errorCode: 11005 errorMsg:hResponse return code != 0

**Comment by MimikFc7** [comment]
try sdk 
implementation 'com.tuya.smart:tuyasmart:3.11.0'
implementation 'com.tuya.smart:tuyasmart-ipc-camera-middleware:3.11.1r119'
implementation 'com.tuya.smart:tuyasmart-ipc-camera-v2:3.11.0r119'
implementation 'com.tuya.smart:tuyasmart-ipc-camera-utils:3.11.0r119'
implementation 'com.tuya.smart:tuyasmart-tuyaHybridContainer:1.0.0'
implementation 'com.github.wendux:DSBridge-Android:3.0-SNAPSHOT'
implementation 'com.tuya.smart:tuyasmart-ipc-devicecontrol:3.11.0r119'
implementation "com.tuya.smart:tuyaCamera:3.11.0r119h2"

onDeviceStatusChanged bf9b1a74420f82893f6ca5
D/Tuya: TuyaSmartHardwareManager online: true; devId: bf9b1a74420f82893f6ca5
D/Tuya: TuyaSmartHardwareManager add new gw
D/Tuya: LocalControlModel queryDp: {}
D/Tuya: TuyaHardwareManager {}
D/Tuya: LocalControlNormal localControlNormal
D/Tuya: DeviceEventSender devUpdate
D/Tuya: TuyaDeviceMonitorManager devId: bf9b1a74420f82893f6ca5 online:true
D/Tuya: GwTransferModel hardware control success
D/Tuya: GwTransferModel response devId:bf9b1a74420f82893f6ca5;version: 3.2;data:21;type:16;code:1; time=1566511545928
E/Tuya: TuyaSmartHardwareManager local control devId:bf9b1a74420f82893f6ca5 errorCode: 11005 errorMsg:hResponse return code != 0

**Comment by MimikFc7** [comment]
try a last example
with
com.tuya.smart.camera.ipccamerasdk.p2p.ICameraP2P camera;
ITuyaCameraDevice mDeviceControl;

camera not work

mqtt protocol protocol: 4 topicId: 07200091dc4f223ebd3b data: {"data":{"devId":"07200091dc4f223ebd3b","dps":{"6":2241}},"protocol":4,"s":304778,"t":1566513941}
D/Tuya: TuyaMessageCache the dps isDataUpdated == false
D/Tuya: mqtt protocol success with dps: {"6":2241}
D/Tuya: Device Cloud: true dps: {"6":2241}
D/Tuya: DatabaseMessageStore discardArrived{ssl://m1.tuyaeu.com:8883:com.homealone.app_mb_2cd5fd7f68a6a976868e5c428d1afb0de27156c6d4c1_065590d92dd6ba35c52b913a761e1074:com.homealone.app}, {cd4ab637-aef4-4167-9dce-7310e6817506}
D/Tuya: DatabaseMessageStore discardArrived - Message deleted successfully. - messages in db for this clientHandle 0
D/Tuya: GwTransferModel response devId:bf9b1a74420f82893f6ca5;version: 3.2;data:21;type:16;code:1; time=1566513923378
E/Tuya: TuyaSmartHardwareManager local control devId:bf9b1a74420f82893f6ca5 errorCode: 11005 errorMsg:hResponse return code != 0

**Comment by MimikFc7** [comment]
now camera not working =)) best challenge, not have a camera - not have a trouble =))
in tutc sdk al fine work, i make full camera view, but after update all not work =))

**Comment by Tuya-DJ** [comment]
Please provide devid, localkey for a camera.  let me check it

**Comment by MimikFc7** [comment]
Hello, give for you that only 8 hours ago. please wait.

**Comment by Tuya-DJ** [comment]
hello，i need localkey too

**Comment by MimikFc7** [comment]
> hello，i need localkey too

understand but not have a source code right now, please wait 8 hours =)

**Comment by MimikFc7** [comment]
> hello，i need localkey too,please provide it

bf9b1a74420f82893f6ca5

a31566af224fa107

**Comment by Tuya-DJ** [comment]
camera is not online,  it is not work.

**Comment by MimikFc7** [comment]
> camera is not online, it is not work.

Sorry, lost power, today i change that

**Comment by MimikFc7** [comment]
> camera is not online, it is not work.

Camera is switch to on

**Comment by Tuya-DJ** [comment]
ok ,it is working. now, can you show a video ?

**Comment by MimikFc7** [comment]
> ok ,it is working. now, can you show a video ?

**Comment by MimikFc7** [comment]
video not working does not connect to camera

**Comment by Tuya-DJ** [comment]
demo is ok ,please try it.

**Comment by MimikFc7** [comment]
> demo is ok ,please try it.

Hm ok i check that later, tell mee please what class i must use?

com.tuya.smart.camera.ipccamerasdk.p2p.ICameraP2P
or
TuyaSmartCamera

and what a type ? 1 or 2 ?

**Comment by Tuya-DJ** [comment]
Refer to demo

**Comment by MimikFc7** [comment]
> Refer to demo

ok i try later, i can check that only 8 hours later now i dont have sources, i write about my results, ok?

**Comment by Tuya-DJ** [comment]
OK

**Comment by MimikFc7** [comment]
com.tuya.smart.camera.ipccamerasdk.p2p.ICameraP2P camera
```
D/CAMERASDK: requestWithApiName onSuccess
I/TYSDK: TuyaCameraSDK: [INFO] TYP2pModuleV1 initialized.
D/Tuya: com.tuya.smart.camera.ipccamerasdk.IPCTuyaP2PCamera connect start ... 
D/Tuya: com.tuya.smart.camera.ipccamerasdk.IPCTuyaP2PCamera connect failure ... 
D/CAMERASDK: connect onFailure 0  -1

```

**Comment by MimikFc7** [comment]
So next trouble it's a sharing, can you help me?

**Comment by Tuya-DJ** [comment]
what`s problem?

**Comment by MimikFc7** [comment]
> what`s problem?

https://github.com/TuyaInc/tuyasmart_home_android_sdk/issues/52

that

**Comment by MimikFc7** [comment]
> what`s problem?

Hello about camera iterested moment:

OperationDelegateCallBack  returned file name as JPG when a write mp4 video.

mCameraP2P.stopRecordLocalMp4( new OperationDelegateCallBack()
    {

        @Override
        public void onSuccess(int i, int i1, String s) {
            Log.d(TAG,"localRecordCallback onSuccess "+s);
        s - have a jpg extension - not correct 
        }

        @Override
        public void onFailure(int i, int i1, int i2) {

        }
    }; );

**Comment by MimikFc7** [comment]
> OK

Hello, can are you make firmware for camera: bfa5ca8598afb005f0qsg7

**Comment by MimikFc7** [comment]
Hello! what about camera firmware???

**Comment by Tuya-DJ** [comment]
upgrading

**Comment by Tuya-DJ** [comment]
You can use this jpg as a cover image.

**Comment by MimikFc7** [comment]
> upgrading

Very thanks! Firmware begin update
