### ISSUE TITLE
GVS+IPC SDK APP+001+IPC配网用哪个接口?

### ISSUE THREAD

**Issue by ttxoox** [TuyaInc/tuyasmart_home_android_sdk#63]
我们接入方式是配网SDK+IPC SDK，使用云云对接的方式接入。IPC配网应该用SDK里面的哪个接口，我发现配网需要一个homeid，这个homeid从哪里获取。

**Comment by Tuya-DJ** [comment]
ipc配网和其他wifi设备配网是一样的，EZ，AP不需要走特殊接口，使用配网sdk即可。只有二维码配网，需要参考如下文档：https://tuyainc.github.io/tuyasmart_camera_android_sdk_doc/zh-hans/resource/wifi_config.html

**Comment by ttxoox** [comment]
这里面有一个token，我们之前是采用云端获取的方式获取然后APP组装的，这个是不是也是一样可以这么做？

**Comment by Tuya-DJ** [comment]
可以的

**Comment by ttxoox** [comment]
好的，我试一下
