### ISSUE TITLE
Firebase Sdk  與 Tuya Sdk ？

### ISSUE THREAD

**Issue by William-Chou** [TuyaInc/tuyasmart_home_android_sdk#67]
1. SDK中 是否有init FirebaseMessaging ? 如有的話 可否可以提供一版沒有的？
2. SDk 中 FirebaseMessaging 的版本是？
3. 在Application中 使用 FirebaseMessaging.getInstance().setAutoInitEnabled(true) & Realm.getDefaultInstance()  正常 但加入 TuyaSdk.init(this) 後 , App crash 提示需要加入 FirebaseApp.initializeApp(this) , 但加入 FirebaseApp.initializeApp(this) 後 ,  在Application中 呼叫 Realm.getDefaultInstance() 卻有Realm 的 Exception 如下 , 請問該如何解決？

` io.realm.exceptions.RealmError: Unrecoverable error. /data/data/.../files/default.realm: Encrypted interprocess sharing is currently unsupported.SharedGroup has been opened by pid: 1112. Current pid is 1870. in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101`

**Comment by mimimumu** [comment]
你好。这个问题似乎是你集成realm 的问题。可以到关于realm的github里找一下是否有相关的解决办法。
