### ISSUE TITLE
關於低功率camera live(playback) 連線喚醒？

### ISSUE THREAD

**Issue by William-Chou** [TuyaInc/tuyasmart_home_android_sdk#68]
你好 目前發現在連線 低功率camera(有battery)時 有無法喚醒的情況？
已有下 mDeviceControl.wirelessWake(localkey, devId) 的方法, 
請問是缺少哪些部分 才能喚醒 低功率camera 呢？

**Comment by Tuya-DJ** [comment]
设备有没有唤醒过

**Comment by William-Chou** [comment]
沒有喚醒過

**Comment by Tuya-DJ** [comment]
那请问一下，mqtt是通的吗，比如dp点数据下发都OK不

**Comment by William-Chou** [comment]
mCameraP2P.createDevice 有做,   然後送 mDeviceControl.wirelessWake(localkey, devId) 之後 跑到 mCameraP2P.connect 的時候就會進onFailure了 所以沒有 mCameraP2P.startPreview

**Comment by Tuya-DJ** [comment]
请问一下，设备绑在demo上是什么情况

**Comment by William-Chou** [comment]
在Demo App上 camera 都顯示綠燈在線
但連線 就如同我上述 (此時 camera 實體燈號 為 無燈燈) 
假如 在 camera 前晃動 camera 實體燈號 改為 紅燈亮半秒後 恆亮藍燈 此時 連線/回放 均為正常

**Comment by Tuya-DJ** [comment]
首先demo中，在connect的函数体内，保证调用到wirelesswake函数，然后你做这么一个操作，camera灯灭掉之后，打开 app上的 camera预览页面。查看现象：camera灯号是否会从红灯->蓝灯，此时连线/回放 是否正常

**Comment by William-Chou** [comment]
你好 已解決 
      if (null != mDeviceControl && null != deviceBean
                && null != deviceBean.getUiName()
                && deviceBean.getUiName().equals("CameraPbList")) {
            String localkey = deviceBean.getLocalKey();
            mDeviceControl.wirelessWake(localkey, devId);
        }
原因是不知為何 deviceBean.getUiName() == null。所以沒有呼叫 mDeviceControl.wirelessWake(localkey, devId);
