### ISSUE TITLE
SDK as Service

### ISSUE THREAD

**Issue by mytuya** [TuyaInc/tuyasmart_home_android_sdk#7]
When I run SDK as a service, I get the following issue. 

GwBroadcastMonitorModel update
TuyaSmartHardwareManager check service status
TuyaSmartHardwareManager checkService
GwTransferModel try to startService
GwTransferModel service started
GwBroadcastMonitorModel try to startMonitor service
GwBroadcastMonitorModel service started
GwBroadcastMonitorModel update
TuyaSmartHardwareManager check service status
TuyaSmartHardwareManager checkService
GwTransferModel try to startService
GwTransferModel service started
GwBroadcastMonitorModel try to startMonitor service
GwBroadcastMonitorModel service started
GwBroadcastMonitorModel update
TuyaSmartHardwareManager check service status
TuyaSmartHardwareManager checkService

**Comment by xionghai123** [comment]
hello，we do not start so much services, just log

**Comment by mytuya** [comment]
Hello we run our app as a foreground service on an android tv box. Will the sdk stop working if the app is running in the background? Updates such as onDpUpdate and onStatusChange will that be affected?

**Comment by mytuya** [comment]
Is there a work around if the SDK stops working while the app is in the background?

**Comment by LuckyStar121** [comment]
@mytuya Did you solve your problem? Anyone can solve this problem, I just met this problem.
Help me please.
