### ISSUE TITLE
註冊流程中單獨確認驗證碼？

### ISSUE THREAD

**Issue by William-Chou** [TuyaInc/tuyasmart_home_android_sdk#70]
在線上商店中的塗鴉智能APP其註冊帳號流程中,使用信箱註冊並輸入信箱且取得驗證碼後,可以單獨輸入確認驗證碼後 再 輸入需註冊的密碼,但在提供的SDK Demo 中 卻是 驗證碼 與 密碼 一同送出 confirm ,想詢問該如何才能像線上商店的app那樣 可以單獨確認驗證碼後再輸入其需註冊的密碼 呢？

**Comment by mimimumu** [comment]
涂鸦智能app界面的流程上有把验证码 和密码页面分开。
在验证码输入完成后校验验证码，然后再把验证码和密码一同送出。

sdk暂时未提供该接口。我们已经记录这个case。后续考虑是否放开该功能。
