### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by tigericon** [TuyaInc/tuyasmart_home_android_sdk#72]
ERROR: Unable to resolve dependency for ':app@release/compileClasspath': Failed to transform file 'tuyasmart-3.11.2.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform

**Comment by tigericon** [comment]
项目转换AndroidX报错  不能解决吗 ？

**Comment by NextApp** [comment]
support Android X 3.19.1
