### ISSUE TITLE
Failed to resolve: com.tuya.smart:tuyaCamera:3.0.6

### ISSUE THREAD

**Issue by EdifierX** [TuyaInc/tuyasmart_home_android_sdk#77]
从APP控制平台下载的build.gradle，3.0.3依赖不了??
![image](https://user-images.githubusercontent.com/26271167/71609916-340d6200-2bc7-11ea-8da7-47ef91d3941a.png)

**Comment by Tuya-DJ** [comment]
app控制平台的build.gradle是哪里下载的?请发一下链接

**Comment by EdifierX** [comment]
https://iot.tuya.com/oem/sdk?id=32234

**Comment by Tuya-DJ** [comment]
https://github.com/TuyaInc/tuyasmart_camera_android_sdk 你可以参考这块文档
