### ISSUE TITLE
登录接口异常问题

### ISSUE THREAD

**Issue by RedSun001** [TuyaInc/tuyasmart_home_android_sdk#8]
调用的这个方法TuyaHomeSdk.getUserInstance().loginWithPhonePassword("86", "***", "***", new ILoginCallback() {}
Android报错为java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference

麻烦请给予指导 谢谢~

**Comment by NextApp** [comment]
可能是没有初始化导致的，TuyaHomeSdk.init？
