### ISSUE TITLE
获取视频流数据？

### ISSUE THREAD

**Issue by William-Chou** [TuyaInc/tuyasmart_home_android_sdk#80]
設置 mCameraP2P.registorOnP2PCameraListener(this); 可以從 onReceiveFrameYUVData 獲取影像資料 , 但若未設置 mCameraP2P.generateCameraView(monitor) 的話, 則onReceiveFrameYUVData不會被調用, 請問有方法可以不設置 mCameraP2P.generateCameraView 取影像資料 的方法嗎？

P.s 目前自製播放器 使用是TextureView 所以並未 extends GLSurfaceView

**Comment by Tuya-DJ** [comment]
目前是不可以的

**Comment by Tuya-DJ** [comment]
你可以不使用view传进来，把继承IRegistorIOTCListener接口的类传进来就可以，比如activity继承这个IRegistorIOTCListener接口就能得到回调
