### ISSUE TITLE
Couldn't find .so library

### ISSUE THREAD

**Issue by hendyevan** [TuyaInc/tuyasmart_home_android_sdk#84]
Hi im integrating Tuya SDK with my app.
I have set app key, app secret, security image and gradle based on documentation in https://tuyainc.github.io/tuyasmart_home_android_sdk_doc/en/.
But when i run it gives me an error :

> couldn't find DSO to load: libc++_shared.so

in gradle im using 
`ndk {
            abiFilters "armeabi", "x86_64","x86"
        }`

**Comment by NextApp** [comment]
Sorry , the SDK do not support the x86 now
