### ISSUE TITLE
房间添加设备问题

### ISSUE THREAD

**Issue by RedSun001** [TuyaInc/tuyasmart_home_android_sdk#9]
使用TuyaHomeSdk.newRoomInstance("homeId")  调用 addDevice(String devId, IResultCallback callback);添加设备 显示 permission_denied没有权限 。

麻烦请给予指导  谢谢~

**Comment by hackill** [comment]
homeID 是否有效，先查询一下home列表 ，取有效的homeid

**Comment by RedSun001** [comment]
homeid 3596675
devID 0000000j0y

**Comment by yuhaocan** [comment]
> 使用TuyaHomeSdk.newRoomInstance("homeId") 调用 addDevice(String devId, IResultCallback callback);添加设备 显示 permission_denied没有权限 。
> 
> 麻烦请给予指导 谢谢~



> 使用TuyaHomeSdk.newRoomInstance("homeId") 调用 addDevice(String devId, IResultCallback callback);添加设备 显示 permission_denied没有权限 。
> 
> 麻烦请给予指导 谢谢~

确认添加的homeId是当前账号具有该homeId、以及当前账号是该家庭的管理员和devId是不是真实存在

**Comment by hackill** [comment]
devID 0000000j0y 看样子是你随便写的，要先配网，配网可以拿到这些数据的devId，然后再把设备添加到房间中

**Comment by woodknife2019** [comment]
我们是通过手机app对设备进行的配网，然后获取的该设备虚拟ID，之后反查到的这个devID 0000000j0y

**Comment by hackill** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    我不是很明白你的意思。大致逻辑说明：1、家庭管理，可以进行创建家庭和获取已经创建的家庭的信息 如homebean2、设备配网，配网时，会根据homeid 把设备配置再某个homeid中3、设备配置成功后   才可以进行添加指定的某些房间中。你所进行的操作 addDevice 就是把设备添加到某个房间中 属于房间管理。按照你所说的已经进行过设备配网，你可以通过家庭管理先查询一下 家庭的信息，是可以查到已经配网过的设备的。详见文档中家庭管理homebean中有这些信息。如果查不到devID 0000000j0y 就说明这个设备未在你目前使用的账号体系下配网过。再则 0000000j0y 明显不符合我们的devID命名格式 应该是不对的。Ps: 申请的appkey 和secret ，相当于一个新的应用。如果是在我们的app上添加的设备 不会出现在你们申请的账号下面的。在2019年01月29日 15:14，woodknife2019<notifications@github.com> 写道： 


我们是通过手机app对设备进行的配网，然后获取的该设备虚拟ID，之后反查到的这个devID 0000000j0y



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.





        font{
            line-height: 1.6;
        }

**Comment by woodknife2019** [comment]
ok，理解了。1.之前在手机app的进行设备的配网绑定是对我们现在的工作是没有用的  2.需要用代码 创建家庭－－设备配网－－查询家庭信息可获取到devID.

**Comment by woodknife2019** [comment]
ok，理解了。1.之前在手机app的进行设备的配网绑定是对我们现在的工作是没有用的  2.需要用代码 创建家庭－－设备配网－－查询家庭信息可获取到devID.
